### ISSUE TITLE
code 

### ISSUE THREAD

**Issue by Teacherxuyl** [BIT-MCS/DRL-EC3#1]
Traceback (most recent call last):
  File "E:\github代码\DRL-EC3-main\experiments\train.py", line 319, in <module>
    train(arglist, log)
  File "E:\github代码\DRL-EC3-main\experiments\train.py", line 117, in train
    summary = Summary(sess, envs[0].log_dir)
IndexError: list index out of range
What causes this problem when I run experiments/train.py? How can I solve this problem?Have a nice day.

**Comment by hkskn24** [comment]
The value of arglist.num_actor_workers is set to 0 (experiments/train.py line 43), so the length of envs is 0 ("envs = [Env(log) for _ in range(arglist.num_actor_workers)]", experiments/train.py line 112) , and access " envs[0] " can cause this error.
Maybe change the value of num_actor_workers can solve this problem.
